# Generated by Django 3.2.20 on 2023-09-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='default.jpg', upload_to='book_covers'),
        ),
    ]
