# Generated by Django 3.2.20 on 2023-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='media/default.jpg', upload_to='media/book_covers'),
        ),
    ]
