# Generated by Django 3.2.20 on 2023-09-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20230913_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category_images/default.jpg', upload_to='category_images'),
        ),
    ]
