# Generated by Django 3.2.20 on 2023-09-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='book_covers/default.jpg', upload_to='book_covers'),
        ),
    ]
