# Generated by Django 3.2.20 on 2023-09-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_alter_book_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
